server:
  port: 3000

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://<ip>:<port>/<name>?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username:
    password:
    hikari:
      connection-test-query: SELECT 1 # 测试连接是否有效
      connection-timeout: 60000 # 连接超时时间
      idle-timeout: 600000 # 连接空闲超时时间
      max-lifetime: 1800000 # 连接最大生命周期
      maximum-pool-size: 12 # 连接池最大连接数
      minimum-idle: 10 # 连接池最小空闲连接数
      pool-name: SpringHikariCP
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true # 下划线转驼峰
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志输出到控制台
